package com.mycompany.praktikum_9;
import javax.swing.JOptionPane;

/**
 *
 * @author BlueBird
 */
public class TambahDataPanel extends javax.swing.JPanel {

    /**
     * Creates new form TambahDataPanel
     */
    private Mahasiswa mahasiswaToUpdate;
    private MainJFrame mainFrame;
    
    public TambahDataPanel(MainJFrame mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;
    }

    private void clearForm(){
        namaTextField.setText("");
        nimTextField.setText("");
        lakilakiRadioButton.setSelected(false);
        perempuanRadioButton.setSelected(false);
        statusCheckBox.setSelected(false);
    }
    
    public void updateForm(Mahasiswa mhs){
        namaTextField.setText(mhs.getNama());
        nimTextField.setText(mhs.getNim());
        prodiComboBox.setSelectedItem(mhs.getProdi());
        if(mhs.getJenisKelamin().equals("Laki-Laki")){
            lakilakiRadioButton.setSelected(true);
        }else{
            perempuanRadioButton.setSelected(true);
        }
        statusCheckBox.setSelected(mhs.isIsActive());
        this.mahasiswaToUpdate = mhs;
        titleLabel.setText("Update Data Mahasiswa");
        kirimButton.setText("Update"); 
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kirimButton = new javax.swing.JButton();
        namaTextField = new javax.swing.JTextField();
        nimTextField = new javax.swing.JTextField();
        statusCheckBox = new javax.swing.JCheckBox();
        lakilakiRadioButton = new javax.swing.JRadioButton();
        perempuanRadioButton = new javax.swing.JRadioButton();
        prodiComboBox = new javax.swing.JComboBox<>();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(530, 400));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleLabel.setText("Tambah Data Mahasiswa");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Nama");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("NIM");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Prodi");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Jenis Kelamin");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Status");

        kirimButton.setBackground(new java.awt.Color(51, 51, 255));
        kirimButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        kirimButton.setForeground(new java.awt.Color(255, 255, 255));
        kirimButton.setText("Kirim");
        kirimButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kirimButtonActionPerformed(evt);
            }
        });

        namaTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        namaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaTextFieldActionPerformed(evt);
            }
        });

        nimTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        statusCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        statusCheckBox.setText("Aktif");

        buttonGroup1.add(lakilakiRadioButton);
        lakilakiRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lakilakiRadioButton.setText("Laki Laki");
        lakilakiRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakilakiRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(perempuanRadioButton);
        perempuanRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        perempuanRadioButton.setText("Perempuan");
        perempuanRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perempuanRadioButtonActionPerformed(evt);
            }
        });

        prodiComboBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        prodiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S1 Teknik Informatika", "S1 Teknik Elektro", "D3 Teknik Elektro", "S1 Teknik Sipil", "D3 Teknik Sipil", "S1 Teknik Kimia", "D3 Teknik Kimia", "D3 Teknologi Pulp dan Kertas", "S1 Arsitektur", "S1 Teknik Mesin", "D3 Teknik Mesin", "D4 Akuntansi Perpajakan" }));
        prodiComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodiComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(kirimButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(statusCheckBox)
                            .addComponent(namaTextField)
                            .addComponent(nimTextField)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lakilakiRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(perempuanRadioButton))
                            .addComponent(prodiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(titleLabel)
                .addGap(0, 125, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel2)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel3)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel4)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel5)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(titleLabel)
                        .addGap(18, 18, 18)
                        .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(nimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(prodiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lakilakiRadioButton)
                            .addComponent(perempuanRadioButton))
                        .addGap(18, 18, 18)
                        .addComponent(statusCheckBox)))
                .addGap(28, 28, 28)
                .addComponent(kirimButton)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void kirimButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kirimButtonActionPerformed
        // TODO add your handling code here:
        String nama = namaTextField.getText();
        String nim = nimTextField.getText();
        String prodi = (String) prodiComboBox.getSelectedItem();
        String jenisKelamin = lakilakiRadioButton.isSelected() ? "Laki-Laki" : "Perempuan" ; 
        boolean isActive = statusCheckBox.isSelected();
        if (nama.isEmpty() || nim.isEmpty() || (!lakilakiRadioButton.isSelected() && !perempuanRadioButton.isSelected()) || !isActive){
            JOptionPane.showMessageDialog(this, "Gagal menambahkan data!\nSilahkan lengkapi data terlebih dahulu");
            return;
        }
        try{
            long nimLong = Long.parseLong(nim);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Gagal menambahkan data!\nNIM harus berupa angka");
            return;
        }
        
        if(mahasiswaToUpdate == null){
            Mahasiswa mahasiswaDuplikat = null;
            for(Mahasiswa mhs : Mahasiswa.mahasiswas){
                if(mhs.getNim().equals(nim)){
                    mahasiswaDuplikat = mhs;
                    break;
                }
            }
            if(mahasiswaDuplikat == null){
                Mahasiswa mahasiswa = new Mahasiswa(nama, nim, prodi, jenisKelamin, isActive);
                Mahasiswa.mahasiswas.add(mahasiswa);
                JOptionPane.showMessageDialog(this, "Berhasil menambahkan data mahasiswa " + nama);
                clearForm();
            }else {
                String pesan = "NIM " + nim + " sudah terdaftar untuk nama " + mahasiswaDuplikat.getNama();
                JOptionPane.showMessageDialog(this, pesan);
            }
        }else {
            if(!mahasiswaToUpdate.getNim().equals(nim)){
                for(Mahasiswa mhs : Mahasiswa.mahasiswas){
                    if(mhs.getNim().equals(nim) && mhs != mahasiswaToUpdate){
                        String pesan = "NIM " + nim + " sudah terdaftar untuk nama " + mhs.getNama();
                        JOptionPane.showMessageDialog(this, pesan);
                        return;
                    }
                }
            }
            mahasiswaToUpdate.setNama(nama);
            mahasiswaToUpdate.setNim(nim);
            mahasiswaToUpdate.setProdi(prodi);
            mahasiswaToUpdate.setJenisKelamin(jenisKelamin);
            mahasiswaToUpdate.setIsActive(isActive);
            JOptionPane.showMessageDialog(this, "Data berhasil di-update");
            mainFrame.changeMainPanel(new LihatDataPanel(mainFrame));
        }
    }//GEN-LAST:event_kirimButtonActionPerformed

    private void namaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaTextFieldActionPerformed

    private void lakilakiRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lakilakiRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lakilakiRadioButtonActionPerformed

    private void prodiComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodiComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodiComboBoxActionPerformed

    private void perempuanRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perempuanRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perempuanRadioButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kirimButton;
    private javax.swing.JRadioButton lakilakiRadioButton;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JTextField nimTextField;
    private javax.swing.JRadioButton perempuanRadioButton;
    private javax.swing.JComboBox<String> prodiComboBox;
    private javax.swing.JCheckBox statusCheckBox;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
