/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.praktikum_8;

/**
 *
 * @author User
 */
public class Kalkulator1 extends javax.swing.JFrame {

    /**
     * Creates new form Kalkulator1
     */
    
    private String karakter = "";
    private double bil1, bil2, hasil;
    private int pilihOperator;
    
    
    public Kalkulator1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void angka5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka5ButtonActionPerformed
        tombolAngkaActionPerformed("5");
    }//GEN-LAST:event_angka5ButtonActionPerformed

    private void angka4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka4ButtonActionPerformed
        tombolAngkaActionPerformed("4");
    }//GEN-LAST:event_angka4ButtonActionPerformed

    private void angka6ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka6ButtonActionPerformed
        tombolAngkaActionPerformed("6");
    }//GEN-LAST:event_angka6ButtonActionPerformed

    private void kurangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangButtonActionPerformed
        if(karakter.isEmpty()){
            karakter = "-";
            outputField.setText(karakter);
        }else{
            tombolOperatorActionPerformed("-");
            pilihOperator = 2;
        }
    }//GEN-LAST:event_kurangButtonActionPerformed

    private void tambahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahButtonActionPerformed
        tombolOperatorActionPerformed("+");
        pilihOperator = 1;
    }//GEN-LAST:event_tambahButtonActionPerformed

    private void angka3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka3ButtonActionPerformed
        tombolAngkaActionPerformed("3");
    }//GEN-LAST:event_angka3ButtonActionPerformed

    private void angka1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka1ButtonActionPerformed
        tombolAngkaActionPerformed("1");
    }//GEN-LAST:event_angka1ButtonActionPerformed

    private void angka2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka2ButtonActionPerformed
        tombolAngkaActionPerformed("2");
    }//GEN-LAST:event_angka2ButtonActionPerformed

    private void hasilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilButtonActionPerformed
        if (karakter.isEmpty() || karakter.equals("-")){
            return;
        }       
        bil2 = Double.parseDouble(karakter);
        switch(pilihOperator){
            case 1: hasil = bil1 + bil2; break;
            case 2: hasil = bil1 - bil2; break;
            case 3: hasil = bil1 * bil2; break;
            case 4: 
                if(bil2 == 0){
                    outputField.setText("error: pembagian dengan 0");
                    karakter = "";
                    bil1 = bil2 = hasil = pilihOperator = 0;
                    return;                    
                } else{
                    hasil = bil1 / bil2;
                }
                break;
            default: break;            
        }
        
        if(hasil % 1 == 0){
            outputField.setText(String.valueOf((int)hasil));
            karakter = Integer.toString((int) hasil);
        }else{
            outputField.setText(String.valueOf(hasil));
            karakter = Double.toString(hasil);
        }
    }//GEN-LAST:event_hasilButtonActionPerformed

    private void outputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputFieldActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        karakter = "";
        bil1 = bil2 = hasil = 0;
        outputField.setText(karakter);
    }//GEN-LAST:event_clearButtonActionPerformed

    private void persenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persenButtonActionPerformed
        if (karakter.isEmpty() || karakter.equals("-")){
            return;
        }       
        double nilai = Double.parseDouble(karakter) / 100;

        if(hasil % 1 == 0){
            outputField.setText(String.valueOf((int)hasil));
            karakter = Integer.toString((int) hasil);
        }else{
            outputField.setText(String.valueOf(hasil));
            karakter = Double.toString(hasil);
        }
    }//GEN-LAST:event_persenButtonActionPerformed

    private void backspaceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backspaceButtonActionPerformed
        if(!karakter.isEmpty()){
            karakter = karakter.substring(0, karakter.length() - 1);
            outputField.setText(karakter.isEmpty() ? "" : karakter);
        }
    }//GEN-LAST:event_backspaceButtonActionPerformed

    private void bagiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagiButtonActionPerformed
        tombolOperatorActionPerformed("÷");
        pilihOperator = 4;
    }//GEN-LAST:event_bagiButtonActionPerformed

    private void angka7ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka7ButtonActionPerformed
        tombolAngkaActionPerformed("7");
    }//GEN-LAST:event_angka7ButtonActionPerformed

    private void angka8ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka8ButtonActionPerformed
        tombolAngkaActionPerformed("8");
    }//GEN-LAST:event_angka8ButtonActionPerformed

    private void angka9ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka9ButtonActionPerformed
        tombolAngkaActionPerformed("9");
    }//GEN-LAST:event_angka9ButtonActionPerformed

    private void angka0ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka0ButtonActionPerformed
        tombolAngkaActionPerformed("0");
    }//GEN-LAST:event_angka0ButtonActionPerformed

    private void kaliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaliButtonActionPerformed
        tombolOperatorActionPerformed("×");
        pilihOperator = 3; 
    }//GEN-LAST:event_kaliButtonActionPerformed

    private void komaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_komaButtonActionPerformed
        if (!karakter.contains(".")) {
            if (karakter.isEmpty()) {
                karakter = "0.";
            } else {
                karakter += ".";
            }
            outputField.setText(karakter);
        }
    }//GEN-LAST:event_komaButtonActionPerformed
    
    private void tombolAngkaActionPerformed(String angka){
        karakter += angka;
        outputField.setText(karakter);
    }
    
    private void tombolOperatorActionPerformed(String operator){
        if (karakter.isEmpty() || karakter.equals("-")){
            return;
        }
        bil1 = Double.parseDouble(karakter);
        outputField.setText(operator);
        karakter = "";
    }  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalkulator1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}