/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.praktikum_8;

/**
 *
 * @author User
 */
public class Kalkulator1 extends javax.swing.JFrame {

    /**
     * Creates new form Kalkulator1
     */
    
    private String karakter = "";
    private double bil1, bil2, hasil;
    private int pilihOperator;
    
    
    public Kalkulator1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        angka5Button = new javax.swing.JButton();
        angka4Button = new javax.swing.JButton();
        angka6Button = new javax.swing.JButton();
        kurangButton = new javax.swing.JButton();
        tambahButton = new javax.swing.JButton();
        angka3Button = new javax.swing.JButton();
        angka1Button = new javax.swing.JButton();
        angka2Button = new javax.swing.JButton();
        hasilButton = new javax.swing.JButton();
        outputField = new javax.swing.JTextField();
        clearButton = new javax.swing.JButton();
        persenButton = new javax.swing.JButton();
        backspaceButton = new javax.swing.JButton();
        bagiButton = new javax.swing.JButton();
        angka7Button = new javax.swing.JButton();
        angka8Button = new javax.swing.JButton();
        angka9Button = new javax.swing.JButton();
        angka0Button = new javax.swing.JButton();
        kaliButton = new javax.swing.JButton();
        komaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkulator");
        setResizable(false);

        angka5Button.setBackground(new java.awt.Color(242, 242, 242));
        angka5Button.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        angka5Button.setForeground(new java.awt.Color(100, 100, 100));
        angka5Button.setText("5");
        angka5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka5ButtonActionPerformed(evt);
            }
        });

        angka4Button.setBackground(new java.awt.Color(242, 242, 242));
        angka4Button.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        angka4Button.setForeground(new java.awt.Color(100, 100, 100));
        angka4Button.setText("4");
        angka4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka4ButtonActionPerformed(evt);
            }
        });

        angka6Button.setBackground(new java.awt.Color(242, 242, 242));
        angka6Button.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        angka6Button.setForeground(new java.awt.Color(100, 100, 100));
        angka6Button.setText("6");
        angka6Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka6ButtonActionPerformed(evt);
            }
        });

        kurangButton.setBackground(new java.awt.Color(0, 51, 204));
        kurangButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        kurangButton.setForeground(new java.awt.Color(235, 236, 229));
        kurangButton.setText("-");
        kurangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurangButtonActionPerformed(evt);
            }
        });

        tambahButton.setBackground(new java.awt.Color(0, 51, 204));
        tambahButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tambahButton.setForeground(new java.awt.Color(235, 236, 229));
        tambahButton.setText("+");
        tambahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahButtonActionPerformed(evt);
            }
        });

        angka3Button.setBackground(new java.awt.Color(242, 242, 242));
        angka3Button.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        angka3Button.setForeground(new java.awt.Color(100, 100, 100));
        angka3Button.setText("3");
        angka3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka3ButtonActionPerformed(evt);
            }
        });

        angka1Button.setBackground(new java.awt.Color(242, 242, 242));
        angka1Button.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        angka1Button.setForeground(new java.awt.Color(100, 100, 100));
        angka1Button.setText("1");
        angka1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka1ButtonActionPerformed(evt);
            }
        });

        angka2Button.setBackground(new java.awt.Color(242, 242, 242));
        angka2Button.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        angka2Button.setForeground(new java.awt.Color(100, 100, 100));
        angka2Button.setText("2");
        angka2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka2ButtonActionPerformed(evt);
            }
        });

        hasilButton.setBackground(new java.awt.Color(0, 51, 204));
        hasilButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        hasilButton.setForeground(new java.awt.Color(235, 236, 229));
        hasilButton.setText("=");
        hasilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilButtonActionPerformed(evt);
            }
        });

        outputField.setEditable(false);
        outputField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        outputField.setForeground(new java.awt.Color(100, 100, 100));
        outputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputFieldActionPerformed(evt);
            }
        });

        clearButton.setBackground(new java.awt.Color(0, 51, 204));
        clearButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        clearButton.setForeground(new java.awt.Color(235, 236, 229));
        clearButton.setText("C");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        persenButton.setBackground(new java.awt.Color(0, 51, 204));
        persenButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        persenButton.setForeground(new java.awt.Color(235, 236, 229));
        persenButton.setText("%");
        persenButton.setToolTipText("");
        persenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persenButtonActionPerformed(evt);
            }
        });

        backspaceButton.setBackground(new java.awt.Color(0, 51, 204));
        backspaceButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        backspaceButton.setForeground(new java.awt.Color(235, 236, 229));
        backspaceButton.setText("D");
        backspaceButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        backspaceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backspaceButtonActionPerformed(evt);
            }
        });

        bagiButton.setBackground(new java.awt.Color(0, 51, 204));
        bagiButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bagiButton.setForeground(new java.awt.Color(235, 236, 229));
        bagiButton.setText("÷");
        bagiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagiButtonActionPerformed(evt);
            }
        });

        angka7Button.setBackground(new java.awt.Color(242, 242, 242));
        angka7Button.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        angka7Button.setForeground(new java.awt.Color(100, 100, 100));
        angka7Button.setText("7");
        angka7Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka7ButtonActionPerformed(evt);
            }
        });

        angka8Button.setBackground(new java.awt.Color(242, 242, 242));
        angka8Button.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        angka8Button.setForeground(new java.awt.Color(100, 100, 100));
        angka8Button.setText("8");
        angka8Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka8ButtonActionPerformed(evt);
            }
        });

        angka9Button.setBackground(new java.awt.Color(242, 242, 242));
        angka9Button.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        angka9Button.setForeground(new java.awt.Color(100, 100, 100));
        angka9Button.setText("9");
        angka9Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka9ButtonActionPerformed(evt);
            }
        });

        angka0Button.setBackground(new java.awt.Color(242, 242, 242));
        angka0Button.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        angka0Button.setForeground(new java.awt.Color(100, 100, 100));
        angka0Button.setText("0");
        angka0Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka0ButtonActionPerformed(evt);
            }
        });

        kaliButton.setBackground(new java.awt.Color(0, 51, 204));
        kaliButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        kaliButton.setForeground(new java.awt.Color(235, 236, 229));
        kaliButton.setText("×");
        kaliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaliButtonActionPerformed(evt);
            }
        });

        komaButton.setBackground(new java.awt.Color(242, 242, 242));
        komaButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        komaButton.setForeground(new java.awt.Color(100, 100, 100));
        komaButton.setText(".");
        komaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                komaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(angka0Button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(komaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(hasilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(angka1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(angka2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(angka3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(tambahButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(angka4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(angka5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(angka6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(kurangButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(angka7Button, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(angka8Button, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(angka9Button, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(kaliButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(backspaceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(persenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(bagiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(outputField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(outputField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backspaceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bagiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(persenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(angka7Button, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(angka8Button, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(angka9Button, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kaliButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(angka4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(angka5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(angka6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kurangButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(angka1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(angka2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(angka3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambahButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(angka0Button, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(komaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hasilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void angka5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka5ButtonActionPerformed
        tombolAngkaActionPerformed("5");
    }//GEN-LAST:event_angka5ButtonActionPerformed

    private void angka4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka4ButtonActionPerformed
        tombolAngkaActionPerformed("4");
    }//GEN-LAST:event_angka4ButtonActionPerformed

    private void angka6ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka6ButtonActionPerformed
        tombolAngkaActionPerformed("6");
    }//GEN-LAST:event_angka6ButtonActionPerformed

    private void kurangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangButtonActionPerformed
        if(karakter.isEmpty()){
            karakter = "-";
            outputField.setText(karakter);
        }else{
            tombolOperatorActionPerformed("-");
            pilihOperator = 2;
        }
    }//GEN-LAST:event_kurangButtonActionPerformed

    private void tambahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahButtonActionPerformed
        tombolOperatorActionPerformed("+");
        pilihOperator = 1;
    }//GEN-LAST:event_tambahButtonActionPerformed

    private void angka3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka3ButtonActionPerformed
        tombolAngkaActionPerformed("3");
    }//GEN-LAST:event_angka3ButtonActionPerformed

    private void angka1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka1ButtonActionPerformed
        tombolAngkaActionPerformed("1");
    }//GEN-LAST:event_angka1ButtonActionPerformed

    private void angka2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka2ButtonActionPerformed
        tombolAngkaActionPerformed("2");
    }//GEN-LAST:event_angka2ButtonActionPerformed

    private void hasilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilButtonActionPerformed
        if (karakter.isEmpty() || karakter.equals("-")){
            return;
        }       
        bil2 = Double.parseDouble(karakter);
        switch(pilihOperator){
            case 1: hasil = bil1 + bil2; break;
            case 2: hasil = bil1 - bil2; break;
            case 3: hasil = bil1 * bil2; break;
            case 4: 
                if(bil2 == 0){
                    outputField.setText("error: pembagian dengan 0");
                    karakter = "";
                    bil1 = bil2 = hasil = pilihOperator = 0;
                    return;                    
                } else{
                    hasil = bil1 / bil2;
                }
                break;
            default: break;            
        }
        
        if(hasil % 1 == 0){
            outputField.setText(String.valueOf((int)hasil));
            karakter = Integer.toString((int) hasil);
        }else{
            outputField.setText(String.valueOf(hasil));
            karakter = Double.toString(hasil);
        }
    }//GEN-LAST:event_hasilButtonActionPerformed

    private void outputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputFieldActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        karakter = "";
        bil1 = bil2 = hasil = 0;
        outputField.setText(karakter);
    }//GEN-LAST:event_clearButtonActionPerformed

    private void persenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persenButtonActionPerformed
        if (karakter.isEmpty() || karakter.equals("-")){
            return;
        }       
        double nilai = Double.parseDouble(karakter) / 100;

        if(hasil % 1 == 0){
            outputField.setText(String.valueOf((int)hasil));
            karakter = Integer.toString((int) hasil);
        }else{
            outputField.setText(String.valueOf(hasil));
            karakter = Double.toString(hasil);
        }
    }//GEN-LAST:event_persenButtonActionPerformed

    private void backspaceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backspaceButtonActionPerformed
        if(!karakter.isEmpty()){
            karakter = karakter.substring(0, karakter.length() - 1);
            outputField.setText(karakter.isEmpty() ? "" : karakter);
        }
    }//GEN-LAST:event_backspaceButtonActionPerformed

    private void bagiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagiButtonActionPerformed
        tombolOperatorActionPerformed("÷");
        pilihOperator = 4;
    }//GEN-LAST:event_bagiButtonActionPerformed

    private void angka7ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka7ButtonActionPerformed
        tombolAngkaActionPerformed("7");
    }//GEN-LAST:event_angka7ButtonActionPerformed

    private void angka8ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka8ButtonActionPerformed
        tombolAngkaActionPerformed("8");
    }//GEN-LAST:event_angka8ButtonActionPerformed

    private void angka9ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka9ButtonActionPerformed
        tombolAngkaActionPerformed("9");
    }//GEN-LAST:event_angka9ButtonActionPerformed

    private void angka0ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka0ButtonActionPerformed
        tombolAngkaActionPerformed("0");
    }//GEN-LAST:event_angka0ButtonActionPerformed

    private void kaliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaliButtonActionPerformed
        tombolOperatorActionPerformed("×");
        pilihOperator = 3; 
    }//GEN-LAST:event_kaliButtonActionPerformed

    private void komaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_komaButtonActionPerformed
        if (!karakter.contains(".")) {
            if (karakter.isEmpty()) {
                karakter = "0.";
            } else {
                karakter += ".";
            }
            outputField.setText(karakter);
        }
    }//GEN-LAST:event_komaButtonActionPerformed
    
    private void tombolAngkaActionPerformed(String angka){
        karakter += angka;
        outputField.setText(karakter);
    }
    
    private void tombolOperatorActionPerformed(String operator){
        if (karakter.isEmpty() || karakter.equals("-")){
            return;
        }
        bil1 = Double.parseDouble(karakter);
        outputField.setText(operator);
        karakter = "";
    }  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalkulator1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton angka0Button;
    private javax.swing.JButton angka1Button;
    private javax.swing.JButton angka2Button;
    private javax.swing.JButton angka3Button;
    private javax.swing.JButton angka4Button;
    private javax.swing.JButton angka5Button;
    private javax.swing.JButton angka6Button;
    private javax.swing.JButton angka7Button;
    private javax.swing.JButton angka8Button;
    private javax.swing.JButton angka9Button;
    private javax.swing.JButton backspaceButton;
    private javax.swing.JButton bagiButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton hasilButton;
    private javax.swing.JButton kaliButton;
    private javax.swing.JButton komaButton;
    private javax.swing.JButton kurangButton;
    private javax.swing.JTextField outputField;
    private javax.swing.JButton persenButton;
    private javax.swing.JButton tambahButton;
    // End of variables declaration//GEN-END:variables
}